# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tower < Formula
  desc ""
  homepage "https://github.com/nimbox/tower"
  version "0.1.2"

  on_macos do
    url "https://github.com/nimbox/tower/releases/download/v0.1.2/tower_0.1.2_darwin_all.tar.gz"
    sha256 "9bdab98b1e4fee12b628155f6b182361e8fa30e12d502c9c7c26738201127b48"

    define_method(:install) do
      bin.install "tower"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/tower/releases/download/v0.1.2/tower_0.1.2_linux_amd64.tar.gz"
      sha256 "52acebe3429dd7f489dad7f257ebc48daa0620fc833c845aae81c71f3192e39e"
      define_method(:install) do
        bin.install "tower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbox/tower/releases/download/v0.1.2/tower_0.1.2_linux_arm64.tar.gz"
      sha256 "50fc1b339a48df50e1c8d1946312a7a993b21631f5d131148e8dcc37634b9a45"
      define_method(:install) do
        bin.install "tower"
      end
    end
  end
end
