# This file was generated by GoReleaser. DO NOT EDIT.
cask "tower" do
  require_relative "../lib/private_strategy"

  version "0.1.14"

  on_macos do
    sha256 "47d7c49f1b6f22da6b632791f8e3fbcae52215db08627b4643da67606c6183c2"
    url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_darwin_all.tar.gz",
        verified: "github.com/nimbox/tower/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
  end
  on_linux do
    on_arm do
      sha256 "9e0b327bd87213eafae2343bf83be82ec119b598996c65e62b87e89cfdae0976"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nimbox/tower/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "c8735d5a17f69890341f047b715a929b5449bd1f35e7551de348d7df8c150c7c"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nimbox/tower/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "tower"
  desc "Command line for the nimbox tower"
  homepage "https://github.com/nimbox/tower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tower"
  bash_completion "completions/tower.bash"
  fish_completion "completions/tower.fish"
  zsh_completion "completions/_tower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tower"]
    end
  end

  # No zap stanza required
end
