# This file was generated by GoReleaser. DO NOT EDIT.
cask "tower" do
  require_relative "../lib/private_strategy"

  version "0.3.0"

  on_macos do
    sha256 "9b1c6435ca118119e8c017bcfaf01be3064e1ca0f932f2a323da0e6f42956af5"
    url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_darwin_all.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
  end
  on_linux do
    on_arm do
      sha256 "469a74c3e2a89efad23079d053193bb04bec21ee781586ae7013e85aab8dde13"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "674b9e6889f7851655656e97dbd823000575fe51fd1592350a8844263c62d5bc"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "tower"
  desc "Command line for the nimbox tower"
  homepage "https://github.com/nimbox/tower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tower"
  bash_completion "completions/tower.bash"
  fish_completion "completions/tower.fish"
  zsh_completion "completions/_tower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tower"]
    end
  end

  # No zap stanza required
end
