# This file was generated by GoReleaser. DO NOT EDIT.
cask "tower" do
  require_relative "../lib/private_strategy"

  version "0.2.0"

  on_macos do
    sha256 "c78423bc0ff4db434d7b7151663e7d24559871cbeb886c968b12cbf26fa209ed"
    url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_darwin_all.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
  end
  on_linux do
    on_arm do
      sha256 "40d3512b1ada554e3b108bd04d876057db923fcfc391bc7415ed76c4ddec1c39"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "ad092129a3761828cef5c506d23333126db7c3e15d3e7e04b34bc7a5e197ee6d"
      url "https://github.com/nimbox/tower/releases/download/v#{version}/tower_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "tower"
  desc "Command line for the nimbox tower"
  homepage "https://github.com/nimbox/tower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tower"
  bash_completion "completions/tower.bash"
  fish_completion "completions/tower.fish"
  zsh_completion "completions/_tower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tower"]
    end
  end

  # No zap stanza required
end
